import streamlit as st
import pandas as pd
import os
import sys
from utils.theme import apply_custom_theme
from utils.navigation import render_top_nav

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from database.repositories import AuditRepository

st.set_page_config(page_title="Decision History | RecoverAI", layout="wide")
apply_custom_theme()
render_top_nav()

st.markdown("<h1>Decision History</h1>", unsafe_allow_html=True)
st.markdown("<p><b>Every important decision made by RecoverAI is recorded here for transparency and review.</b></p>", unsafe_allow_html=True)

st.markdown("""
<div style="background-color: #111827; padding: 1.5rem; border-radius: 8px; border: 1px solid #1F2937; margin-bottom: 2rem;">
    <h4 style="margin-top: 0; color: #E5E7EB; font-size: 14px;">What information is available here?</h4>
    <ul style="color: #9CA3AF; font-size: 14px; margin-bottom: 0;">
        <li><b>What happened</b> &mdash; the action or validation performed</li>
        <li><b>When it happened</b> &mdash; the exact timestamp</li>
        <li><b>What action was considered</b> &mdash; the decision generated by the AI</li>
        <li><b>What safety checks were applied</b> &mdash; how the guardrails evaluated the decision</li>
        <li><b>Why the final outcome was produced</b> &mdash; the reasoning for allowing, blocking, or escalating</li>
    </ul>
</div>
""", unsafe_allow_html=True)

logs = AuditRepository.get_all_logs()

if not logs:
    st.info("No audit logs found.")
else:
    df = pd.DataFrame(logs)
    df = df.sort_values(by='timestamp', ascending=False)
    
    from database.repositories import CaseRepository
    cases = CaseRepository.get_all_cases()
    customer_map = {c['_id']: c.get('customer_id', 'Unknown') for c in cases}
    
    df['Customer'] = df['case_id'].map(lambda x: customer_map.get(x, 'Unknown'))
    
    display_df = df[['timestamp', 'Customer', 'stage', 'actor', 'decision', 'reason', 'case_id']]
    display_df.columns = ['Timestamp', 'Customer', 'Stage', 'Actor', 'Decision', 'Reason', 'full_case_id']

    col1, col2, col3 = st.columns(3)
    with col1:
        case_filter = st.text_input("Customer Filter")
    with col2:
        stage_filter = st.multiselect("Stage", display_df['Stage'].unique())
    with col3:
        decision_filter = st.multiselect("Decision", display_df['Decision'].unique())
        
    filtered_df = display_df.copy()
    if case_filter:
        filtered_df = filtered_df[filtered_df['full_case_id'].str.contains(case_filter, case=False, na=False)]
    if stage_filter:
        filtered_df = filtered_df[filtered_df['Stage'].isin(stage_filter)]
    if decision_filter:
        filtered_df = filtered_df[filtered_df['Decision'].isin(decision_filter)]

    st.dataframe(
        filtered_df.drop('full_case_id', axis=1),
        use_container_width=True,
        hide_index=True
    )
    
    st.markdown("<hr style='border-top: 1px solid #1F2937;'><br>", unsafe_allow_html=True)
    st.download_button(
        label="Download CSV Export",
        data=filtered_df.drop('full_case_id', axis=1).to_csv(index=False).encode('utf-8'),
        file_name='recoverai_audit_log.csv',
        mime='text/csv',
    )
